#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ft8716_fhd_dsi_cmd_shift5me.o lcm_dispsys_gpio.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc



