#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += rm67195_fhd_dsi_cmd_shift6m.o lcm_poweron_drv.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc



